// Code generated by "github.com/maru44/simdb/gen"; DO NOT EDIT.

package point

import (
	"fmt"
	"sync"
)

type (
	Pt struct {
		Name    string
		Email   string
		age     uint
		IsValid bool
	}

	Pts struct {
		data map[int]*Pt
		sync.RWMutex
	}
)

func NewPts() Pts {
	return Pts{
		data: map[int]*Pt{},
	}
}

func (t *Pts) List() map[int]*Pt {
	t.RLock()
	defer t.RUnlock()
	return t.data
}

func (t *Pts) Exists(id int) bool {
	t.RLock()
	defer t.RUnlock()
	_, ok := t.data[id]
	return ok
}

func (t *Pts) Get(id int) (*Pt, error) {
	t.RLock()
	defer t.RUnlock()
	v, ok := t.data[id]
	if !ok {
		return nil, fmt.Errorf("Not Exists: %v", id)
	}
	return v, nil
}

func (t *Pts) Load(id int) (*Pt, bool) {
	t.RLock()
	defer t.RUnlock()
	value, ok := t.data[id]
	return value, ok
}

func (t *Pts) Insert(id int, value *Pt) error {
	t.Lock()
	defer t.Unlock()
	if _, ok := t.data[id]; ok {
		return fmt.Errorf("Duplicate Entry: %v", id)
	}
	t.data[id] = value
	return nil
}

func (t *Pts) BulkInsert(values map[int]*Pt) error {
	t.Lock()
	defer t.Unlock()
	for id := range values {
		if _, ok := t.data[id]; ok {
			return fmt.Errorf("Duplicate Entry: %v", id)
		}
	}
	for id, value := range values {
		t.data[id] = value
	}
	return nil
}

func (t *Pts) Update(id int, value *Pt) error {
	t.Lock()
	defer t.Unlock()
	if _, ok := t.data[id]; !ok {
		return fmt.Errorf("Does not exists: %v", id)
	}
	t.data[id] = value
	return nil
}

func (t *Pts) UpdateName(id int, value string) error {
	t.Lock()
	defer t.Unlock()
	data, ok := t.data[id]
	if !ok {
		return fmt.Errorf("Does not exists: %v", id)
	}
	data.Name = value
	return nil
}

func (t *Pts) UpdateEmail(id int, value string) error {
	t.Lock()
	defer t.Unlock()
	data, ok := t.data[id]
	if !ok {
		return fmt.Errorf("Does not exists: %v", id)
	}
	data.Email = value
	return nil
}

func (t *Pts) Updateage(id int, value uint) error {
	t.Lock()
	defer t.Unlock()
	data, ok := t.data[id]
	if !ok {
		return fmt.Errorf("Does not exists: %v", id)
	}
	data.age = value
	return nil
}

func (t *Pts) UpdateIsValid(id int, value bool) error {
	t.Lock()
	defer t.Unlock()
	data, ok := t.data[id]
	if !ok {
		return fmt.Errorf("Does not exists: %v", id)
	}
	data.IsValid = value
	return nil
}

func (t *Pts) Upsert(id int, value *Pt) {
	t.Lock()
	defer t.Unlock()
	t.data[id] = value
}

func (t *Pts) BulkUpsert(values map[int]*Pt) {
	t.Lock()
	defer t.Unlock()
	for id, value := range values {
		t.data[id] = value
	}
}

func (t *Pts) Delete(id int) {
	t.Lock()
	defer t.Unlock()
	delete(t.data, id)
}

func (t *Pts) BulkDelete(ids []int) {
	t.Lock()
	defer t.Unlock()
	for _, id := range ids {
		delete(t.data, id)
	}
}

func (t *Pts) Truncate() {
	t.Lock()
	defer t.Unlock()
	t.data = map[int]*Pt{}
}
