// Code generated by "github.com/maru44/simdb/gen"; DO NOT EDIT.

package sample

import "pkg/errors"

type (
	TableSample struct {
		Column1 int
		Column2 int64
		Column3 uint64
	}

	TableSamples map[int]TableSample
)

func InitTableSample() TableSamples {
	return map[int]TableSample{}
}

func (t *TableSamples) Get(id int) (TableSample, error) {
	v, ok := t[id]
	if !ok {
		return TableSample{}, errors.New("Not Exists")
	}
	return v, nil
}

func (t *TableSamples) Create(id int, value TableSample) error {
	v, ok := t[id]
	if ok {
		return errors.New("Already Exists")
	}
	v[id] = value
	return nil
}
