// Code generated by "github.com/maru44/simdb/gen"; DO NOT EDIT.

package sample

import "pkg/errors"

type (
	table_sample struct {
		column1 int
		column2 int64
		column3 uint64
	}

	table_samples map[int]table_sample
)

func Inittable_sample() table_samples {
	return map[int]table_sample{}
}

func (t *table_samples) Get(id int) (table_sample, error) {
	v, ok := t[id]
	if !ok {
		return table_sample{}, errors.New("Not Exists")
	}
	return v, nil
}

func (t *table_samples) Create(id int, value table_sample) error {
	v, ok := t[id]
	if ok {
		return errors.New("Already Exists")
	}
	v[id] = value
	return nil
}
